# ---- GitHubæ–‡ä»¶æºé…ç½? ----
# GitHubç”¨æˆ·å?(ä¸æ˜¯æ˜µç§°), æ³¨æ„å¤§å°å†?
GitHubUserName: first19326
# GitHubä¸»é?˜ä»“åº“åç§?
GitHubRepositories: Hexo-LiveForCode


# ---- åŸºç?€ä¿¡æ¯é…ç½® ----
# åšä¸»åç§°, æ–‡ç« åç¼€å’Œä¸»é¡µå›¾ç‰‡ä¸Šéƒ½ä¼šä½¿ç”¨æ­¤åç§?
BlogUser: Live For Code
# ç”¨æˆ·å¤´åƒURL
BlogAvatar: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/image/sidebar/avatar.jpg
# åˆ›å»ºæ—¶é—´
BlogStartDate: "2020-01-01"


# ---- ç½‘ç«™é…ç½® ----
# å½“å‰é¡µå¤±å»ç„¦ç‚?, é¡µé¢Titleæ˜¾ç¤ºæ–‡å­—
WebsiteTitleBlur: (â—Â´ê’³`â—?) Hi, Live For Code
# å½“å‰é¡µå¤±å»ç„¦ç‚?, é¡µé¢Titleå˜åŒ–, å»¶æ—¶æ—¶é—´, å•ä½æ¯?ç§?
WebsiteTitleBlurTimeOut: 500
# å½“å‰é¡µè·å–ç„¦ç‚?, é¡µé¢Titleæ˜¾ç¤ºæ–‡å­—, æ˜¾ç¤ºåå»¶æ—¶æ¢å¤åŸTitle
WebsiteTitleFocus: (*Â´âˆ‡ï½€*) æ¬¢è¿å›æ¥!
# å½“å‰é¡µè·å–ç„¦ç‚?, é¡µé¢titleå˜åŒ–, å»¶æ—¶æ—¶é—´, å•ä½æ¯?ç§?
WebsiteTitleFocusTimeOut: 1000
# ç½‘ç«™å›¾æ ‡
WebsiteFavicon: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/image/website/logo.png


# ---- è¿›åº¦æ¡é…ç½? ----
ProgressBar:
  id: topProgressBar
  color: "#77B6FF"
  height: 2px
  duration: 0.2


# ---- Loadingé…ç½® ----
Loading: 
  rebound: 
    tension: 16
    friction: 5
  spinner: 
    id: spinner
    radius: 90
    sides: 3
    depth: 4
    colors: 
      background: "#F0F0F0"
      stroke: "#272633"
      base: null
      child: "#272633"
    # When false the spring will reverse normally.
    alwaysForward: true
    # A number from 0.1 to 0.9 || null for full rotation. 
    restAt: 0.5
    renderBase: false


# ---- é¡µé¢åŠ¨æ•ˆé…ç½® ----
# true || false, æ˜?å¦æ¸²æŸ“ä¸»é¡µå¤´å›¾åŠ¨æ•?
HomeHeaderAnimationRendered: true
# ä¸»é¡µå¤´å›¾åŠ¨æ•ˆè®¾ç½®
HomeHeaderAnimation:    
  radius: 15
  density: 0.2
  # é¢œè‰²è®¾ç½®, "random" ä¸ºéšæœºé?œè‰²
  color: rgba(255, 255, 255, .2)
  clearOffset: 0.3
# true || false, æ˜?å¦æ¸²æŸ“æ–‡ç« è?¦æƒ…é¡µå¤´å›¾åŠ¨æ•?
ArticleHeaderAnimationRendered: false
# æ–‡ç« è¯¦æƒ…é¡µå¤´å›¾åŠ¨æ•ˆè?¾ç½® 
ArticleHeaderAnimation: 
  triW: 14
  triH: 20
  neighbours: 
    - side
    - top
    - bottom
  speedTrailAppear: .1
  speedTrailDisappear: .1
  speedTriOpen: 1
  trailMaxLength: 30
  trailIntervalCreation: 100
  delayBeforeDisappear: 2
  colors: 
    - "#96EDA6"
    - "#5BC6A9"
    - "#38668C"
    - "#374D84"
    - "#BED5CB"
    - "#62ADC6"
    - "#8EE5DE"
    - "#304E7B"
# true || false, æ˜?å¦æ¸²æŸ“èƒŒæ™?åŠ¨æ•ˆ
BackAnimationRendered: true
# true || false, IEæµè?ˆå™¨æ˜?å¦æ¸²æŸ“èƒŒæ™?åŠ¨æ•ˆï¼ˆé»˜è®¤ä¸ºfalseï¼?
IEBrowserBackAnimationRendered: false
# èƒŒæ™¯åŠ¨æ•ˆè®¾ç½®
BackAnimation:
  colorSaturation: 60%
  colorBrightness: 50%
  colorAlpha: 0.5
  colorCycleSpeed: 5
  verticalPosition: random
  horizontalSpeed: 200
  ribbonCount: 3
  strokeSize: 0
  parallaxAmount: -0.2
  animateSections: true


# ---- ä¸»é¡µé…ç½® ----
# ä¸»é¡µå›¾ç‰‡URL, æ¨èå°ºå?? >= 1920 * 1080, æ”?æŒå?šå¼ , æ¯æ?¡åˆ·æ–°éšæœºè?¾ç½®ä¸€å¼?
HomeHeaderImage: 
  - https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/image/header/home.jpg
  - https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/image/header/home.jpeg
# ä¸»é¡µå¤´å›¾ä¸Šçš„æ ‡è??, è®¾ç½®æ­¤é€‰é¡¹ä¼šå›ºå®šæ˜¾ç¤ºæ–‡å­?, é»˜è?¤ä¸ºç©?, è‡?åŠ¨è·å–ä¸€å?
HomeBannerText: ""


# ---- æ–‡ç« è¯¦æƒ…é¡µé…ç½? ----
# æ–‡ç« è¯¦æƒ…é¡µå›¾ç‰‡URL, æ”?æŒå?šå¼ , æ¯æ?¡åˆ·æ–°éšæœºè?¾ç½®ä¸€å¼?
ArticleHeaderImage: 
  - https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/image/header/article.jpg


# ---- å…¶ä»–é¡µé¢é…ç½® ----
# å…¶ä»–é¡µé¢å¤´å›¾ä¸Šçš„æ ‡è??, è®¾ç½®æ­¤é€‰é¡¹ä¼šå›ºå®šæ˜¾ç¤ºæ–‡å­?, é»˜è?¤ä¸ºç©?, è‡?åŠ¨è·å–ä¸€å?
OtherBannerText: ""


# ---- èœå•é…ç½® ----
# å½“é“¾æ¥åœ°å€ä¸?''æ—?, åˆ™é“¾æ¥è‡ªåŠ¨è?¾ç½®ä¸ºå¤±æ•?
# èœå•åˆ—è¡¨
MenuList:
  -
    name: é¦–é¡µ
    href: /
  - 
    name: æ ‡ç??
    href: /tag
  - 
    name: åˆ†ç±»
    href: /category
  -
    name: å½’æ¡£
    href: /archive
  -
    name: èµèµ
    href: /donate
  -
    name: å…³äº
    href: /about
  -
    name: è®¢é˜…
    href: /atom.xml
    target: _blank
  -
    name: æœç´¢
    href: ""
    class: search
  -
    name: ç•™è¨€æ?
    href: /comment
  -
    name: å‹æƒ…é“¾æ¥
    href: /friend
# èœå•é“¾æ¥
MenuLink:
  -
    icon: icon-weibo
    url: ""
  -
    icon: icon-wechat
    url: ""
  -
    icon: icon-qq
    url: ""
  -
    icon: icon-github
    url: https://github.com/first19326


# ---- é¡µè„šé…ç½® ----
# é¡µè„šæ ·å¼
FooterStyle: 2
# é¡µè„šæ ‡è??
BottomText: 
  # å›¾æ ‡  
  icon: like-fill
  # å›¾æ ‡å·¦ä¾§æ–‡å­—
  left: äººç”Ÿè‹¥åªå¦‚åˆè§?
  # å›¾æ ‡å³ä¾§æ–‡å­—
  right: ä½•äº‹ç§‹é?æ‚²ç”»æ‰‡  
# æ˜?å¦æ˜¾ç¤ºä¸»é¢˜ä¿¡æ?
ThemeInfo: true 


# ---- æ§åˆ¶å°è¾“å‡? ----
ConsoleList:
  -
    - Based on cnblogs theme SimpleMemory.
    - ""
  -
    - "SimpleMemory Author:"
    - BNDong
  -
    - "Theme:"
    - LiveForCode


# ---- å­—ä½“å›¾æ ‡æ‰©å±• ----
FontIconExtend: ""


# ---- èµèµé…ç½® ----
Donate: 
  paypal : ""
  bitcoin: ""
  alipay : https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/image/donate/alipay.png
  wechat : https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/image/donate/wechat.png


# ---- Code Style ----
Code: 
  style: normal


# ---- Algoliaé…ç½® ----
Search:
  applicationID: 010C3EANT8
  apiKey: c7abab9f11b79102b9aff7fe6d41447d
  indexName: Notes
  hits:
    page: 10
  labels:
    placeholder: æœç´¢
    empty: æœ?å‘ç°ä¸? ã€?${query}ã€? ç›¸å…³çš„å†…å®?
    stats: ${hits} æ¡ç›¸å…³æ¡ç›?ï¼Œä½¿ç”¨äº† ${time} æ¯?ç§?


# ---- Valineé…ç½® ----
Valine: 
  switch: true
  el: .comments-content
  appId: srhKtvWPQTWYKh3qX8G8M7v0-gzGzoHsz
  appKey: 8uVSP1q6UlALVC5igYfIfv2h
  placeholder: ä½ æ˜¯æˆ‘ä¸€ç”Ÿåªä¼šé‡è§ä¸€æ¬¡çš„æƒŠå–œ...
  avatar: mm
  meta: nick,mail,link
  requiredFields: nick,mail
  pageSize: 5
  lang: zh-cn
  visitor: true
  enableQQ: true


# ---- Tocboté…ç½® ----
Tocbot: 
  switch: true
  tocSelector: .toc
  contentSelector: .article-body
  headingSelector: h1, h2, h3, h4, h5
  headingsOffset: 0
  scrollSmooth: true
  scrollSmoothOffset: -5
  positionFixedSelector: .toc
  positionFixedClass: toc-fixed


# ---- Requireé…ç½® ----
Require:
  baseUrl: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/js/
  waitSeconds: 100


# ---- Musicé…ç½® ----
# é»˜è?¤ä¸ºMeting, å€¼åŒ…å«APlayer, Meting
Music: 
  type: Meting
# APlayer
APlayer:
  container: .aplayer
  fixed: true 
  autoplay: false 
  loop: all 
  order: random 
  preload: auto 
  volume: 0.67 
  mutex: true
  lrcType: 3
  audio:
    -
      name: aLIEz
      artist: mizukiï¼ˆç‘è‘µï¼‰
      cover: /music/cover/aLIEz.jpg
      url: /music/song/aLIEz.mp3
      lrc: /music/lrc/aLIEz.lrc
    -
      name: Endless Tears
      artist: CLIFF EDGE
      cover: /music/cover/Endless Tears.jpg
      url: /music/song/Endless Tears.mp3
      lrc: /music/lrc/Endless Tears.lrc
    -
      name: Miracle
      artist: Cascada
      cover: /music/cover/Miracle.jpg
      url: /music/song/Miracle.mp3
      lrc: /music/lrc/Miracle.lrc
    -
      name: Roll The Dice
      artist: é«˜çŠ
      cover: /music/cover/Roll The Dice.jpg
      url: /music/song/Roll The Dice.mp3
      lrc: /music/lrc/Roll The Dice.lrc
    -
      name: See You Again
      artist: Charlie Puth, Wiz Khalifa
      cover: /music/cover/See You Again.jpg
      url: /music/song/See You Again.mp3
      lrc: /music/lrc/See You Again.lrc
    -
      name: Traveling Light
      artist: Joel Hanson, Sara Groves
      cover: /music/cover/Traveling Light.jpg
      url: /music/song/Traveling Light.mp3
      lrc: /music/lrc/Traveling Light.lrc
    -
      name: ç—´å¿ƒç»å??
      artist: æåœ£æ?
      cover: /music/cover/ç—´å¿ƒç»å??.jpg
      url: /music/song/ç—´å¿ƒç»å??.mp3
      lrc: /music/lrc/ç—´å¿ƒç»å??.lrc
    -
      name: å¥½æƒ³å¤§å£°è¯´çˆ±ä½?
      artist: BAADï¼ˆãƒãƒ¼ãƒ‰ï¼?
      cover: /music/cover/å¥½æƒ³å¤§å£°è¯´çˆ±ä½?.jpg
      url: /music/song/å¥½æƒ³å¤§å£°è¯´çˆ±ä½?.mp3
      lrc: /music/lrc/å¥½æƒ³å¤§å£°è¯´çˆ±ä½?.lrc
# Meting
Meting:
  id: "3778678" 
  lrcshow: false 
  server: netease 
  type: playlist 
  fixed: true 
  autoplay: false 
  loop: all 
  order: random 
  preload: auto 
  volume: 0.67 
  mutex: true


# ---- Lazy Load ----
LazyLoad:
  default: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/image/website/lazyload.svg


# ---- Styleé…ç½® ----
Style:
  aplayer: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/APlayer.css
  archive: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/archive.css
  donate: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/donate.css
  fancybox: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/jquery.fancybox.css
  footer: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/footer.css
  iconfont: https://at.alicdn.com/t/font_1546312_l3yohatebw.css
  index: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/index.css
  menuBubble: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/menu-bubble.css
  page: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/page.css
  post: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/post.css
  search: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/search.css
  tocbot: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/tocbot.css
  normal: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/normal.css
  night: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/night.css
  clipboard: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/clipboard.css

# ---- Scripté…ç½® ----
Script:
  aplayer: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/js/APlayer.min.js
  config: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/js/require.config.js
  index: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/js/index.js
  instantSearch: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/js/instantsearch.min.js
  jQuery: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/js/jquery-3.4.1.min.js
  loading: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/js/loading.js
  meting: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/js/Meting.min.js
  iscroll: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/js/iscroll.js
  require: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/js/require.min.js


# ---- Fonté…ç½® ----
Font:
  LongCang: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/font/LongCang.css
  Monda: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/font/Monda.css
  NotoSansSC: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/font/NotoSansSC.css
  Playball: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/font/Playball.css
  PTMono: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/font/PTMono.css
  RobotoSlab: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/font/RobotoSlab.css
  Rosario: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/font/Rosario.css
  UbuntuMono: https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/font/UbuntuMono.css


# ---- æ–‡ç« å°¾ç¼€é…ç½® ----
Suffix: 
  about: ç®€å•åœ°æ´»ç€, è‚†æ„åˆç²¾å½?.


# ---- ä¸»é?˜ä¿¡æ?é…ç½® ----
Theme: 
  url: https://github.com/first19326/Hexo-LiveForCode
  name: Hexo - Live For Code